import { USER_PASSWORD_MIN_LENGTH } from '@ainyc/canonry-contracts'

/** Shipped copy for the pre-router authentication surfaces. */
export const AUTH_COPY = {
  brandName: 'Canonry',
  connecting: 'Connecting to Canonry…',
  apiKeyErrorHeading: 'Could not verify API key access',
  tryAgain: 'Try again',
  signInHeading: 'Sign in to Canonry',
  signIn: 'Sign in',
  usernameLabel: 'Username',
  passwordLabel: 'Password',
  continueWithGoogle: 'Continue with Google',
  checkingSignInOptions: 'Checking sign-in options…',
  usePassword: 'Use a password instead',
  useGoogle: 'Continue with Google instead',
  backToDashboard: 'Back to dashboard',
  backToSignIn: 'Back to sign in',
  invitationHeading: 'You’re invited to Canonry',
  invitationInstruction: 'Use the Google account for the email address that received this invitation.',
  invitationUnavailable: 'This invitation cannot be used right now. Reopen the invitation or ask your administrator for a new one.',
  invitationFailed: 'Invitation sign-in did not complete. Reopen the invitation or ask your administrator for a new one.',
  invitationSignedInInstruction: 'You are already signed in. Sign out before accepting this invitation with its Google account.',
  signOutToAcceptInvitation: 'Sign out to accept invitation',
  createAdministratorHeading: 'Create administrator account',
  setupKeyLabel: 'Setup or root API key',
  confirmPasswordLabel: 'Confirm password',
  createAdministrator: 'Create administrator account',
  creatingAdministrator: 'Creating administrator account…',
  administratorCreatedSignIn: 'Your administrator account was created. Sign in with it to continue.',
  administratorSetupCompleteSignIn: 'Administrator setup is complete. Sign in to continue.',
  googleOptional: 'You can optionally set up Google sign-in in Settings after you sign in.',
  minPasswordHelp: `Use at least ${USER_PASSWORD_MIN_LENGTH} characters.`,
  shortPasswordHelp: `Enter at least ${USER_PASSWORD_MIN_LENGTH} characters.`,
  passwordsDoNotMatch: 'Passwords do not match.',
  incorrectAccountCredentials: 'Incorrect name or password.',
  legacyRecoveryDescription: 'Enter an API key from this Canonry install. This opens the dashboard with that key’s access and does not change the password.',
  apiKeyLabel: 'Canonry API key',
  openDashboard: 'Open dashboard',
  recoverWithApiKey: 'Forgot password? Use API key',
  useDashboardPassword: 'Use dashboard password instead',
  legacySessionExpired: 'Your session expired — please sign in again.',
  signOut: 'Sign out',
} as const
