export {
  getAdAccount,
  searchGeoLocations,
  listConversionPixels,
  listConversionEventSettings,
  listCampaigns,
  getCampaign,
  createCampaign,
  updateCampaign,
  activateCampaign,
  pauseCampaign,
  listAdGroups,
  getAdGroup,
  createAdGroup,
  updateAdGroup,
  activateAdGroup,
  pauseAdGroup,
  listAds,
  getAd,
  createAd,
  updateAd,
  activateAd,
  pauseAd,
  uploadImageFromUrl,
  getAdAccountInsights,
  getCampaignInsights,
  getAdGroupInsights,
} from './ads-client.js'
export {
  OpenAiAdsApiError,
  OpenAiAdsBiddingTypes,
  OpenAiAdsBillingEventTypes,
  OpenAiAdsCreativeTypes,
  OpenAiAdsWriteStatuses,
  parseErrorEnvelope,
} from './types.js'
export type {
  OpenAiAdsAccount,
  OpenAiAdsAccountIntegrityReview,
  OpenAiAdsAccountIntegrityReviewDetails,
  OpenAiAdsAd,
  OpenAiAdsAdGroup,
  OpenAiAdsBiddingType,
  OpenAiAdsBiddingConfig,
  OpenAiAdsBiddingConfigRequest,
  OpenAiAdsBillingEventType,
  OpenAiAdsCampaign,
  OpenAiAdsCampaignBudget,
  OpenAiAdsCampaignBudgetRequest,
  OpenAiAdsCampaignTargetingRequest,
  OpenAiAdsConversionEventSetting,
  OpenAiAdsConversionEventSource,
  OpenAiAdsConversionPixel,
  OpenAiAdsChatCardCreativeRequest,
  OpenAiAdsCreateAdGroupRequest,
  OpenAiAdsCreateAdRequest,
  OpenAiAdsCreateCampaignRequest,
  OpenAiAdsCreative,
  OpenAiAdsCreativeType,
  OpenAiAdsGeoLocation,
  OpenAiAdsGeoSearchResponse,
  OpenAiAdsInsightRow,
  OpenAiAdsInsightHourRange,
  OpenAiAdsInsightsOptions,
  OpenAiAdsListResponse,
  OpenAiAdsLocationTarget,
  OpenAiAdsLocationTargetRequest,
  OpenAiAdsReviewState,
  OpenAiAdsTargeting,
  OpenAiAdsUpdateAdGroupRequest,
  OpenAiAdsUpdateAdRequest,
  OpenAiAdsUpdateCampaignRequest,
  OpenAiAdsUploadImageRequest,
  OpenAiAdsUploadImageResponse,
  OpenAiAdsWriteStatus,
} from './types.js'
export { OPENAI_ADS_API_BASE, OPENAI_ADS_MAX_PAGES, OPENAI_ADS_REQUEST_TIMEOUT_MS } from './constants.js'
