import type { AiReferralTrafficClass, NormalizedTrafficRequest } from '@ainyc/canonry-contracts'
import { AiReferralTrafficClasses, classifyAiReferralTrafficClass } from '@ainyc/canonry-contracts'
import { verifyIpForRule } from './ip-verify.js'
import { DEFAULT_AI_CRAWLER_RULES, DEFAULT_AI_REFERRER_RULES, SELF_TRAFFIC_USER_AGENT_PATTERNS } from './rules.js'
import type {
  ClassifiedAiReferral,
  ClassifiedAiUserFetch,
  ClassifiedCrawler,
} from './types.js'

// Rules with this `purpose` represent per-user, on-demand fetches from an AI
// surface (e.g. ChatGPT-User, Perplexity-User, MistralAI-User) — not bulk
// crawl. Operators care about the distinction: machine crawl is "AI may
// reference my page someday"; user-fetch is "AI is reading my page right now
// because a real user asked." Routed through classifyAiUserFetch, kept out of
// classifyCrawler so the two signals stay disjoint end-to-end.
const USER_FETCH_PURPOSE = 'user-agent'

function normalizeHost(host: string): string {
  return host.trim().toLowerCase().replace(/^www\./, '')
}

function hostMatches(host: string, domain: string): boolean {
  const normalizedHost = normalizeHost(host)
  const normalizedDomain = normalizeHost(domain)
  return normalizedHost === normalizedDomain || normalizedHost.endsWith(`.${normalizedDomain}`)
}

// UTM source values are often a short label rather than a hostname (e.g.
// `utm_source=chatgpt` for `chatgpt.com`). Match against the first DNS label
// of the rule's domain so we don't miss the short form.
function utmTokenMatchesDomain(utmSource: string, domain: string): boolean {
  if (hostMatches(utmSource, domain)) return true
  const normalizedUtm = normalizeHost(utmSource)
  const firstLabel = normalizeHost(domain).split('.')[0]
  return Boolean(firstLabel) && normalizedUtm === firstLabel
}

function hostFromUrl(value: string | null): string | null {
  if (!value) return null
  try {
    return normalizeHost(new URL(value).hostname)
  } catch {
    return null
  }
}

function utmSourceFromQuery(queryString: string | null): string | null {
  if (!queryString) return null
  const params = new URLSearchParams(queryString)
  const source = params.get('utm_source')
  return source ? normalizeHost(source) : null
}

function utmSourceFromUrl(value: string | null): string | null {
  if (!value) return null
  try {
    return utmSourceFromQuery(new URL(value).search.replace(/^\?/, ''))
  } catch {
    return null
  }
}

function paramsFromQuery(queryString: string | null): URLSearchParams | null {
  if (!queryString) return null
  const params = new URLSearchParams(queryString)
  return [...params.keys()].length > 0 ? params : null
}

function paramsFromUrl(value: string | null): URLSearchParams | null {
  if (!value) return null
  try {
    return paramsFromQuery(new URL(value).search.replace(/^\?/, ''))
  } catch {
    return null
  }
}

/**
 * Paid vs organic for a server-side AI referral.
 *
 * Evaluated over EVERY query string on the event, independent of which tier of
 * `classifyAiReferral`'s cascade matched. A paid ChatGPT ad click carries
 * `utm_medium=cpc` on the request while still matching on the referer host, and
 * an edge-cached sub-resource carries the landing URL's UTMs on its referer —
 * so neither query string can be skipped.
 *
 * There is no server-side equivalent of GA4's `channelGroup`, which leaves the
 * UTM tokens as the only discriminator. `organic` therefore means "no paid
 * evidence found", exactly as it does for GA4: an ad click that carries no UTM
 * tags is indistinguishable from an organic click on either surface.
 */
export function classifyAiReferralTrafficClassFromEvent(
  event: NormalizedTrafficRequest,
): AiReferralTrafficClass {
  for (const params of [paramsFromQuery(event.queryString), paramsFromUrl(event.referer)]) {
    if (!params) continue
    const trafficClass = classifyAiReferralTrafficClass({
      source: params.get('utm_source'),
      medium: params.get('utm_medium'),
      channelGroup: null,
      // Carries utm_campaign / utm_content / utm_term to the shared rules.
      landingPage: `/?${params.toString()}`,
    })
    if (trafficClass === AiReferralTrafficClasses.paid) return AiReferralTrafficClasses.paid
  }
  return AiReferralTrafficClasses.organic
}

/**
 * True when the event was generated by Canonry's own tooling (e.g. the AEO
 * auditor crawling a client's sitemap/robots/llms.txt). Such events are not
 * real visitors or third-party crawlers and are dropped from the rollup so our
 * own measurement never inflates a client's traffic counts.
 */
export function isSelfTraffic(event: NormalizedTrafficRequest): boolean {
  const userAgent = event.userAgent?.trim()
  if (!userAgent) return false
  return SELF_TRAFFIC_USER_AGENT_PATTERNS.some((pattern) => pattern.test(userAgent))
}

export function classifyCrawler(event: NormalizedTrafficRequest): ClassifiedCrawler | null {
  const userAgent = event.userAgent?.trim()
  if (!userAgent) return null

  for (const rule of DEFAULT_AI_CRAWLER_RULES) {
    // Skip user-agent (per-user fetch) rules — those route through
    // classifyAiUserFetch into their own bucket. Letting them match here
    // would double-count human-in-the-loop fetches as machine crawl.
    if (rule.purpose === USER_FETCH_PURPOSE) continue
    if (rule.userAgentPatterns.some((pattern) => pattern.test(userAgent))) {
      // UA matched — try to upgrade `claimed_unverified` → `verified` by
      // checking the request's source IP against the operator's
      // published crawler IP ranges. Falls back to `claimed_unverified`
      // when (a) the operator doesn't publish ranges (most LLM
      // operators today), (b) we don't have the IP, or (c) the IP is
      // outside the published set (probable spoofer — UA matches but
      // source isn't really the operator).
      //
      // The verified vs unverified split surfaces in the dashboard via
      // separate `crawler_events_hourly` buckets (verification_status
      // is part of the primary key), so the operator can sort real
      // crawler traffic from spoofed traffic at a glance.
      const verified = verifyIpForRule(event.remoteIp, rule.id)
      return {
        botId: rule.id,
        operator: rule.operator,
        product: rule.product,
        purpose: rule.purpose,
        verificationStatus: verified ? 'verified' : 'claimed_unverified',
        matchedUserAgent: userAgent,
      }
    }
  }

  return null
}

export function classifyAiUserFetch(event: NormalizedTrafficRequest): ClassifiedAiUserFetch | null {
  const userAgent = event.userAgent?.trim()
  if (!userAgent) return null

  for (const rule of DEFAULT_AI_CRAWLER_RULES) {
    if (rule.purpose !== USER_FETCH_PURPOSE) continue
    if (rule.userAgentPatterns.some((pattern) => pattern.test(userAgent))) {
      // Same IP-verification path as classifyCrawler — the operator's
      // published ranges file (e.g. chatgpt-user.json) is what lifts
      // a UA-only match to `verified`.
      const verified = verifyIpForRule(event.remoteIp, rule.id)
      return {
        botId: rule.id,
        operator: rule.operator,
        product: rule.product,
        verificationStatus: verified ? 'verified' : 'claimed_unverified',
        matchedUserAgent: userAgent,
      }
    }
  }

  return null
}

export function classifyAiReferral(event: NormalizedTrafficRequest): ClassifiedAiReferral | null {
  // Independent of the evidence cascade below: the tier that identifies WHICH
  // engine sent the visit says nothing about whether the visit was paid for.
  const trafficClass = classifyAiReferralTrafficClassFromEvent(event)

  const refererHost = hostFromUrl(event.referer)
  if (refererHost) {
    const rule = DEFAULT_AI_REFERRER_RULES.find((candidate) => hostMatches(refererHost, candidate.domain))
    if (rule) {
      return {
        operator: rule.operator,
        product: rule.product,
        sourceDomain: refererHost,
        evidenceType: 'referer',
        trafficClass,
      }
    }
  }

  const utmSource = utmSourceFromQuery(event.queryString)
  if (utmSource) {
    const rule = DEFAULT_AI_REFERRER_RULES.find((candidate) => utmTokenMatchesDomain(utmSource, candidate.domain))
    if (rule) {
      return {
        operator: rule.operator,
        product: rule.product,
        sourceDomain: utmSource,
        evidenceType: 'utm',
        trafficClass,
      }
    }
  }

  // Edge-cached pages serve the HTML hit from the CDN; only the cache-busting
  // sub-resource requests (JS chunks, fonts, etc.) reach the origin. Those
  // requests carry the original landing-URL UTM in their referer's query
  // string, so we look there too — without it we lose ~all human AI-referral
  // signal on cached sites.
  const refererUtmSource = utmSourceFromUrl(event.referer)
  if (refererUtmSource) {
    const rule = DEFAULT_AI_REFERRER_RULES.find((candidate) => utmTokenMatchesDomain(refererUtmSource, candidate.domain))
    if (rule) {
      return {
        operator: rule.operator,
        product: rule.product,
        sourceDomain: refererUtmSource,
        evidenceType: 'referer-utm',
        trafficClass,
      }
    }
  }

  return null
}
